config/routes.rb
SwiftypeIntegrationDemo::Application.routes.draw do
  resources :posts, :except => :index
  match '/search' => 'search#search', :via => [ :get, :post ]
  root :to => 'posts#index'
end

app/models/create_or_update_swiftype_document.rb
class CreateOrUpdateSwiftypeDocument
  attr_reader :post
  
  def initialize(post)
    @post = post
  end
  
  def run  
    url = Rails.application.routes.url_helpers.post_url(post)
    client = Swiftype::Client.new
    client.create_or_update_document(ENV['SWIFTYPE_ENGINE_SLUG'],
                                     post.model_name.singular, #This assumes that the your engine uses "post" as a document type. You can replace it with any document type defined in your engine
                                     {:external_id => post.id,
                                       :fields => [{:name => 'title', :value => post.title, :type => 'string'},
                                                   {:name => 'body', :value => post.body, :type => 'text'},
                                                   {:name => 'url', :value => url, :type => 'enum'},
                                                   {:name => 'created_at', :value => post.created_at.iso8601, :type => 'date'}]})
  end
end

app/models/delete_swiftype_document.rb
class DeleteSwiftypeDocument
attr_reader :post_id

  def initialize(post_id)
    @post_id = post_id
  end

  def run
    client = Swiftype::Client.new
    client.destroy_document(ENV['SWIFTYPE_ENGINE_SLUG'], post.model_name.singular, post_id) #Post.model_name.singular can be replaced with a document type from your engine.
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :body

  after_save :create_swiftype_document
  after_destroy :destroy_swiftype_document

  private
  def create_swiftype_document
    CreateOrUpdateSwiftypeJob.perform_later(self)
  end
    
  def destroy_swiftype_document
    DeleteSwiftypeDocumentJob.perform_later(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :with => :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('created_at desc').limit(10)
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "New post created"
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Post updated"
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/search_controller.rb
# SearchController demonstrates how to do a Swiftype search on your
# server (as opposed to using the JavaScript).
#
# It is not linked to in the app, but you can visit it at /search
class SearchController < ApplicationController
  def search
    if params[:q]
      client = Swiftype::Client.new
      @results = client.search(ENV['SWIFTYPE_ENGINE_SLUG'], params[:q], {:per_page => '10', :page => params[:page] || 1})
      @post_results = @results['post']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Awesome Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<title>
  <% if content_for?(:title) %>
    <%= content_for(:title) %> - My Awesome Blog
  <% else %>
    My Awesome Blog
  <% end %>
</title>

<div id="container">
  <div id="header">
    <div class="left">
      <h1><%= link_to_unless(current_page?(root_path), 'Perfect Blog', root_path) %></h1>
      <h2>By Random Hacker</h2>
    </div>
    <div class="right">
      <form>
        <input type='text' id='st-search-input' class='st-search-input'/>
      </form>
    </div>
    <br style="clear: both">
  </div>

  <% if flash[:notice] %>
    <div class="flash notice"><%= flash[:notice] %></div>
  <% end %>

  <div id="content">
    <div id="st-results-container" class="st-result-listing"></div>
    <%= yield %>
  </div>
</div>

<script type="text/javascript">
$(function() {
  $('#st-search-input').swiftypeSearch({
    resultContainingElement: '#st-results-container',
    engineKey: '<%= ENV['SWIFTYPE_ENGINE_KEY'] %>'
  });
  $('#st-search-input').swiftype({
    engineKey: '<%= ENV['SWIFTYPE_ENGINE_KEY'] %>'
  });
});
</script>
</body>
</html>

app/views/posts/_form.html.erb
<% if f.object.errors.present? %>
<div class="errors">
  <p>There were problems saving your post:</p>
  <ul>
  <% f.object.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :body %>
<%= f.text_area :body %>

app/views/posts/_post.html.erb
<h2><%= link_to_unless(current_page?(post), post.title, post) %></h2>

<div>
  <%= simple_format(post.body) %>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for @post do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <%= submit_tag 'Update' %>
<% end %>

app/views/posts/index.html.erb
<%= render :partial => 'post', :collection => @posts %>

<div>
  <%= link_to 'Create a new post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= form_for @post do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <%= submit_tag 'Create' %>
<% end %>

app/views/posts/show.html.erb
<% content_for(:title) { @post.title } %>

<%= render :partial => 'post', :object => @post %>

<div>
  <%= link_to 'Edit this post', edit_post_path(@post) %>
  <%= button_to 'Delete this post', post_path(@post), :method => 'delete' %>
</div>

app/views/search/search.html.erb
<%= form_tag search_path, :method => :get do %>
  <%= label_tag :q, 'Search:' %>
  <%= text_field_tag :q, params[:q] %>
<% end %>

<% if params[:q] %>
  <% if @post_results.empty? %>
    <p>Sorry, there were no results for your query.</p>
  <% else %>
    <ul class="search_results">
      <% @post_results.each do |post_result| %>
        <li>
          <h3><%= link_to (post_result['highlight'].try(:[], 'title').try(:html_safe) || post_result['title']), post_path(post_result['external_id']) %></h3>
          <%= post_result['highlight'].try(:[], 'body').try(:html_safe) || post_result['body'] %>
        </li>
      <% end %>
    </ul>

    <% if @results.current_page > 1 %>
      <%= link_to '< previous', search_path(:q => params[:q], :page => @results.current_page - 1) %>
    <% end %>

    <% if @results.num_pages > @results.current_page %>
      <%= link_to 'next >', search_path(:q => params[:q], :page => @results.current_page + 1) %>
    <% end %>
  <% end %>
<% end %>